// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalapb/scalapb.proto

#include "scalapb/scalapb.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_scalapb_2fscalapb_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_scalapb_2fscalapb_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_FieldOptions;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_scalapb_2fscalapb_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_MessageOptions;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_scalapb_2fscalapb_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ScalaPbOptions;
}  // namespace protobuf_scalapb_2fscalapb_2eproto
namespace scalapb {
class ScalaPbOptionsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ScalaPbOptions>
      _instance;
} _ScalaPbOptions_default_instance_;
class MessageOptionsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MessageOptions>
      _instance;
} _MessageOptions_default_instance_;
class FieldOptionsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<FieldOptions>
      _instance;
} _FieldOptions_default_instance_;
}  // namespace scalapb
namespace protobuf_scalapb_2fscalapb_2eproto {
static void InitDefaultsScalaPbOptions() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::scalapb::_ScalaPbOptions_default_instance_;
    new (ptr) ::scalapb::ScalaPbOptions();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::scalapb::ScalaPbOptions::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ScalaPbOptions =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsScalaPbOptions}, {}};

static void InitDefaultsMessageOptions() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::scalapb::_MessageOptions_default_instance_;
    new (ptr) ::scalapb::MessageOptions();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::scalapb::MessageOptions::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_MessageOptions =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMessageOptions}, {}};

static void InitDefaultsFieldOptions() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::scalapb::_FieldOptions_default_instance_;
    new (ptr) ::scalapb::FieldOptions();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::scalapb::FieldOptions::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_FieldOptions =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsFieldOptions}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ScalaPbOptions.base);
  ::google::protobuf::internal::InitSCC(&scc_info_MessageOptions.base);
  ::google::protobuf::internal::InitSCC(&scc_info_FieldOptions.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::scalapb::ScalaPbOptions, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::scalapb::ScalaPbOptions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::scalapb::ScalaPbOptions, package_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::scalapb::ScalaPbOptions, flat_package_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::scalapb::ScalaPbOptions, import_),
  0,
  1,
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::scalapb::MessageOptions, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::scalapb::MessageOptions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::scalapb::MessageOptions, extends_),
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::scalapb::FieldOptions, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::scalapb::FieldOptions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::scalapb::FieldOptions, type_),
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::scalapb::ScalaPbOptions)},
  { 11, 17, sizeof(::scalapb::MessageOptions)},
  { 18, 24, sizeof(::scalapb::FieldOptions)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::scalapb::_ScalaPbOptions_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::scalapb::_MessageOptions_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::scalapb::_FieldOptions_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "scalapb/scalapb.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\025scalapb/scalapb.proto\022\007scalapb\032 google"
      "/protobuf/descriptor.proto\"L\n\016ScalaPbOpt"
      "ions\022\024\n\014package_name\030\001 \001(\t\022\024\n\014flat_packa"
      "ge\030\002 \001(\010\022\016\n\006import\030\003 \003(\t\"!\n\016MessageOptio"
      "ns\022\017\n\007extends\030\001 \003(\t\"\034\n\014FieldOptions\022\014\n\004t"
      "ype\030\001 \001(\t:G\n\007options\022\034.google.protobuf.F"
      "ileOptions\030\374\007 \001(\0132\027.scalapb.ScalaPbOptio"
      "ns:J\n\007message\022\037.google.protobuf.MessageO"
      "ptions\030\374\007 \001(\0132\027.scalapb.MessageOptions:D"
      "\n\005field\022\035.google.protobuf.FieldOptions\030\374"
      "\007 \001(\0132\025.scalapb.FieldOptionsB\036\n\034org.mlfl"
      "ow.scalapb_interface"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 460);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "scalapb/scalapb.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobuf_2fdescriptor_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_scalapb_2fscalapb_2eproto
namespace scalapb {

// ===================================================================

void ScalaPbOptions::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ScalaPbOptions::kPackageNameFieldNumber;
const int ScalaPbOptions::kFlatPackageFieldNumber;
const int ScalaPbOptions::kImportFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ScalaPbOptions::ScalaPbOptions()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_scalapb_2fscalapb_2eproto::scc_info_ScalaPbOptions.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:scalapb.ScalaPbOptions)
}
ScalaPbOptions::ScalaPbOptions(const ScalaPbOptions& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      import_(from.import_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  package_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_package_name()) {
    package_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.package_name_);
  }
  flat_package_ = from.flat_package_;
  // @@protoc_insertion_point(copy_constructor:scalapb.ScalaPbOptions)
}

void ScalaPbOptions::SharedCtor() {
  package_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  flat_package_ = false;
}

ScalaPbOptions::~ScalaPbOptions() {
  // @@protoc_insertion_point(destructor:scalapb.ScalaPbOptions)
  SharedDtor();
}

void ScalaPbOptions::SharedDtor() {
  package_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ScalaPbOptions::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ScalaPbOptions::descriptor() {
  ::protobuf_scalapb_2fscalapb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_scalapb_2fscalapb_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ScalaPbOptions& ScalaPbOptions::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_scalapb_2fscalapb_2eproto::scc_info_ScalaPbOptions.base);
  return *internal_default_instance();
}


void ScalaPbOptions::Clear() {
// @@protoc_insertion_point(message_clear_start:scalapb.ScalaPbOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  import_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    package_name_.ClearNonDefaultToEmptyNoArena();
  }
  flat_package_ = false;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ScalaPbOptions::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:scalapb.ScalaPbOptions)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string package_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_package_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->package_name().data(), static_cast<int>(this->package_name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "scalapb.ScalaPbOptions.package_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool flat_package = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_flat_package();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &flat_package_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string import = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_import()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->import(this->import_size() - 1).data(),
            static_cast<int>(this->import(this->import_size() - 1).length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "scalapb.ScalaPbOptions.import");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:scalapb.ScalaPbOptions)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:scalapb.ScalaPbOptions)
  return false;
#undef DO_
}

void ScalaPbOptions::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:scalapb.ScalaPbOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string package_name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->package_name().data(), static_cast<int>(this->package_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "scalapb.ScalaPbOptions.package_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->package_name(), output);
  }

  // optional bool flat_package = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->flat_package(), output);
  }

  // repeated string import = 3;
  for (int i = 0, n = this->import_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->import(i).data(), static_cast<int>(this->import(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "scalapb.ScalaPbOptions.import");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->import(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:scalapb.ScalaPbOptions)
}

::google::protobuf::uint8* ScalaPbOptions::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:scalapb.ScalaPbOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string package_name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->package_name().data(), static_cast<int>(this->package_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "scalapb.ScalaPbOptions.package_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->package_name(), target);
  }

  // optional bool flat_package = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->flat_package(), target);
  }

  // repeated string import = 3;
  for (int i = 0, n = this->import_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->import(i).data(), static_cast<int>(this->import(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "scalapb.ScalaPbOptions.import");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->import(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:scalapb.ScalaPbOptions)
  return target;
}

size_t ScalaPbOptions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:scalapb.ScalaPbOptions)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated string import = 3;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->import_size());
  for (int i = 0, n = this->import_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->import(i));
  }

  if (_has_bits_[0 / 32] & 3u) {
    // optional string package_name = 1;
    if (has_package_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->package_name());
    }

    // optional bool flat_package = 2;
    if (has_flat_package()) {
      total_size += 1 + 1;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ScalaPbOptions::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:scalapb.ScalaPbOptions)
  GOOGLE_DCHECK_NE(&from, this);
  const ScalaPbOptions* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ScalaPbOptions>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:scalapb.ScalaPbOptions)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:scalapb.ScalaPbOptions)
    MergeFrom(*source);
  }
}

void ScalaPbOptions::MergeFrom(const ScalaPbOptions& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:scalapb.ScalaPbOptions)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  import_.MergeFrom(from.import_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_package_name();
      package_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.package_name_);
    }
    if (cached_has_bits & 0x00000002u) {
      flat_package_ = from.flat_package_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ScalaPbOptions::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:scalapb.ScalaPbOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ScalaPbOptions::CopyFrom(const ScalaPbOptions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:scalapb.ScalaPbOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ScalaPbOptions::IsInitialized() const {
  return true;
}

void ScalaPbOptions::Swap(ScalaPbOptions* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ScalaPbOptions::InternalSwap(ScalaPbOptions* other) {
  using std::swap;
  import_.InternalSwap(CastToBase(&other->import_));
  package_name_.Swap(&other->package_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(flat_package_, other->flat_package_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ScalaPbOptions::GetMetadata() const {
  protobuf_scalapb_2fscalapb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_scalapb_2fscalapb_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MessageOptions::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MessageOptions::kExtendsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MessageOptions::MessageOptions()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_scalapb_2fscalapb_2eproto::scc_info_MessageOptions.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:scalapb.MessageOptions)
}
MessageOptions::MessageOptions(const MessageOptions& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      extends_(from.extends_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:scalapb.MessageOptions)
}

void MessageOptions::SharedCtor() {
}

MessageOptions::~MessageOptions() {
  // @@protoc_insertion_point(destructor:scalapb.MessageOptions)
  SharedDtor();
}

void MessageOptions::SharedDtor() {
}

void MessageOptions::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MessageOptions::descriptor() {
  ::protobuf_scalapb_2fscalapb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_scalapb_2fscalapb_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MessageOptions& MessageOptions::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_scalapb_2fscalapb_2eproto::scc_info_MessageOptions.base);
  return *internal_default_instance();
}


void MessageOptions::Clear() {
// @@protoc_insertion_point(message_clear_start:scalapb.MessageOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  extends_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool MessageOptions::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:scalapb.MessageOptions)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string extends = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_extends()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->extends(this->extends_size() - 1).data(),
            static_cast<int>(this->extends(this->extends_size() - 1).length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "scalapb.MessageOptions.extends");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:scalapb.MessageOptions)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:scalapb.MessageOptions)
  return false;
#undef DO_
}

void MessageOptions::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:scalapb.MessageOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string extends = 1;
  for (int i = 0, n = this->extends_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->extends(i).data(), static_cast<int>(this->extends(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "scalapb.MessageOptions.extends");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->extends(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:scalapb.MessageOptions)
}

::google::protobuf::uint8* MessageOptions::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:scalapb.MessageOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string extends = 1;
  for (int i = 0, n = this->extends_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->extends(i).data(), static_cast<int>(this->extends(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "scalapb.MessageOptions.extends");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->extends(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:scalapb.MessageOptions)
  return target;
}

size_t MessageOptions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:scalapb.MessageOptions)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated string extends = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->extends_size());
  for (int i = 0, n = this->extends_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->extends(i));
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MessageOptions::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:scalapb.MessageOptions)
  GOOGLE_DCHECK_NE(&from, this);
  const MessageOptions* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MessageOptions>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:scalapb.MessageOptions)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:scalapb.MessageOptions)
    MergeFrom(*source);
  }
}

void MessageOptions::MergeFrom(const MessageOptions& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:scalapb.MessageOptions)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  extends_.MergeFrom(from.extends_);
}

void MessageOptions::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:scalapb.MessageOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageOptions::CopyFrom(const MessageOptions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:scalapb.MessageOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageOptions::IsInitialized() const {
  return true;
}

void MessageOptions::Swap(MessageOptions* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MessageOptions::InternalSwap(MessageOptions* other) {
  using std::swap;
  extends_.InternalSwap(CastToBase(&other->extends_));
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MessageOptions::GetMetadata() const {
  protobuf_scalapb_2fscalapb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_scalapb_2fscalapb_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void FieldOptions::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FieldOptions::kTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FieldOptions::FieldOptions()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_scalapb_2fscalapb_2eproto::scc_info_FieldOptions.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:scalapb.FieldOptions)
}
FieldOptions::FieldOptions(const FieldOptions& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_type()) {
    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
  // @@protoc_insertion_point(copy_constructor:scalapb.FieldOptions)
}

void FieldOptions::SharedCtor() {
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

FieldOptions::~FieldOptions() {
  // @@protoc_insertion_point(destructor:scalapb.FieldOptions)
  SharedDtor();
}

void FieldOptions::SharedDtor() {
  type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void FieldOptions::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* FieldOptions::descriptor() {
  ::protobuf_scalapb_2fscalapb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_scalapb_2fscalapb_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const FieldOptions& FieldOptions::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_scalapb_2fscalapb_2eproto::scc_info_FieldOptions.base);
  return *internal_default_instance();
}


void FieldOptions::Clear() {
// @@protoc_insertion_point(message_clear_start:scalapb.FieldOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    type_.ClearNonDefaultToEmptyNoArena();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool FieldOptions::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:scalapb.FieldOptions)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->type().data(), static_cast<int>(this->type().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "scalapb.FieldOptions.type");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:scalapb.FieldOptions)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:scalapb.FieldOptions)
  return false;
#undef DO_
}

void FieldOptions::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:scalapb.FieldOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string type = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "scalapb.FieldOptions.type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->type(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:scalapb.FieldOptions)
}

::google::protobuf::uint8* FieldOptions::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:scalapb.FieldOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string type = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "scalapb.FieldOptions.type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->type(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:scalapb.FieldOptions)
  return target;
}

size_t FieldOptions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:scalapb.FieldOptions)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // optional string type = 1;
  if (has_type()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FieldOptions::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:scalapb.FieldOptions)
  GOOGLE_DCHECK_NE(&from, this);
  const FieldOptions* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const FieldOptions>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:scalapb.FieldOptions)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:scalapb.FieldOptions)
    MergeFrom(*source);
  }
}

void FieldOptions::MergeFrom(const FieldOptions& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:scalapb.FieldOptions)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_type()) {
    set_has_type();
    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
}

void FieldOptions::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:scalapb.FieldOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FieldOptions::CopyFrom(const FieldOptions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:scalapb.FieldOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FieldOptions::IsInitialized() const {
  return true;
}

void FieldOptions::Swap(FieldOptions* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FieldOptions::InternalSwap(FieldOptions* other) {
  using std::swap;
  type_.Swap(&other->type_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata FieldOptions::GetMetadata() const {
  protobuf_scalapb_2fscalapb_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_scalapb_2fscalapb_2eproto::file_level_metadata[kIndexInFileMessages];
}

::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::scalapb::ScalaPbOptions >, 11, false >
  options(kOptionsFieldNumber, *::scalapb::ScalaPbOptions::internal_default_instance());
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::scalapb::MessageOptions >, 11, false >
  message(kMessageFieldNumber, *::scalapb::MessageOptions::internal_default_instance());
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::scalapb::FieldOptions >, 11, false >
  field(kFieldFieldNumber, *::scalapb::FieldOptions::internal_default_instance());

// @@protoc_insertion_point(namespace_scope)
}  // namespace scalapb
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::scalapb::ScalaPbOptions* Arena::CreateMaybeMessage< ::scalapb::ScalaPbOptions >(Arena* arena) {
  return Arena::CreateInternal< ::scalapb::ScalaPbOptions >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::scalapb::MessageOptions* Arena::CreateMaybeMessage< ::scalapb::MessageOptions >(Arena* arena) {
  return Arena::CreateInternal< ::scalapb::MessageOptions >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::scalapb::FieldOptions* Arena::CreateMaybeMessage< ::scalapb::FieldOptions >(Arena* arena) {
  return Arena::CreateInternal< ::scalapb::FieldOptions >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
