name: hyperparam_example
channels:
  - defaults
dependencies:
  - python=3.6
  - numpy=1.14.3
  - pandas=0.22.0
  - scikit-learn=0.19.1
  - matplotlib=2.2.2
  - pip:
    - mlflow>=0.5.2
    - click==6.7
    - Gpy==1.9.2
    - GpyOpt==1.2.5
    - tensorflow==1.10.1
    - keras==2.2.2
    - pyDOE==0.3.8
    - hyperopt==0.1

